config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [ :show, :edit, :update, :destroy ]
  def index
    @kittens = Kitten.all
    respond_to do |format|
      # index.html.erb
      format.html
      format.json { render(json: @kittens) }
      format.xml { render(xml: @kittens) }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      # index.html.erb
      format.html
      format.json { render(json: @kitten) }
      format.xml { render(xml: @kitten) }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to(@kitten)
    else
      render(:new, status: :unprocessable_entity)
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to(@kitten)
    else
      render(:edit, status: :unprocessable_entity)
    end
  end

  def destroy
    if @kitten.destroy
      redirect_to(kittens_url, notice: "Kitten data was deleted successfully!")
    else
      redirect_to(kittens_url, alert: "Error deleting kitten: #{@kitten.errors.full_messages.join(", ")}")
    end
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1>Kittens#edit</h1>
<h2> <%= @kitten.name %> </h2>
<%= form_with(model: @kitten, local: true) do |form| %>
  <% if @kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% @kitten.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name%>
    <%= form.text_field :name%>
  </div>

  <div>
    <%= form.label :age%>
    <%= form.number_field :age, in: 1..20, step: 1%>
  </div>

  <div>
    <%= form.label :cuteness%>
    <%= form.number_field :cuteness, in: 1..10, step: 1%>
  </div>

  <div>
    <%= form.label :softness%>
    <%= form.number_field :softness, in: 1..10, step: 1%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= button_to 'Delete', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', kittens_path %>

app/views/kittens/index.html.erb
<h1>Kittens#index</h1>
<%= link_to 'New', new_kitten_path(@kitten) %>

<ol>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten_path(kitten) %> 
    </li>
      <%= button_to 'Delete', kitten, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</ol>

app/views/kittens/new.html.erb
<h1>Kittens#new</h1>
<%= form_with(model: @kitten, local: true) do |form| %>
  <% if @kitten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kitten.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% @kitten.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name%>
    <%= form.text_field :name%>
  </div>

  <div>
    <%= form.label :age%>
    <%= form.number_field :age, in: 1..20, step: 1%>
  </div>

  <div>
    <%= form.label :cuteness%>
    <%= form.number_field :cuteness, in: 1..10, step: 1%>
  </div>

  <div>
    <%= form.label :softness%>
    <%= form.number_field :softness, in: 1..10, step: 1%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<h1>Kittens#show</h1>

<p>Name: <%= @kitten.name %></p>
<p>Age: <%= @kitten.age%></p>
<p>Cuteness: <%= @kitten.cuteness%></p>
<p>Softness: <%= @kitten.softness%></p>
<%= link_to 'Edit', edit_kitten_path(@kitten) %>
<%= button_to 'Delete', @kitten, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>